---
- hosts: localhost
  connection: local

  tasks:

    
    - name: Install Dependencies
      become: true
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present
        update_cache: yes

    - name: Adding GPG key
      become: true
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
    
    - name: Adding Repository
      become: true
      apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present
    
    - name: Update server
      become: true
      apt:
       update_cache: yes
    
    - name: Install docker-ce
      become: true
      apt:
       name: docker-ce
       state: present
       #update_cache: yes
